version: '3'
services:
  web:
    build: 
      context: . #Where to pull the code file and folders from
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: . #Where to pull the code file and folders from
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","test"]